# Generated by Django 3.1.3 on 2020-11-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicacion')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='fecha de creacion')),
                ('autor_id', models.ManyToManyField(to='libro.Autor')),
            ],
        ),
    ]
