# Generated by Django 3.1.3 on 2021-02-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_auto_20210219_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='placas',
            name='No_cedula',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(to='libro.Autor'),
        ),
    ]
